/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vzd.teststuite

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testDummy() {
    }
}
