= Changelog `vzd-cli`

== Version 2.1.0
- CLI Interface wurde weitgehend überarbeiten un vereinfacht, s. Dokumentation
- Self-Update Funktion wurde implementiert, s. `vzd-cli update`
- Erste simple Web-GUI wurde hinzugefügt, s. `vzd-cli gui`
- Neu: ApoVZD Unterstützung über `vzd-cli apo`
- `vzd-cli admin <tu|ru|pu> login` wurde komplett überarbeitet
- `vzd-cli admin <tu|ru|pu> token` ersetzt `vzd-cli admin auth`
- Neuer Befehl: `vzd-cli admin <tu|ru|pu> search`: schnelle, intuitive Suche nach Einträgen
- Neuer Befehl: `vzd-cli admin <tu|ru|pu> show <TELEMATIK_ID>`: zeigt den gesamten Eintrag in verschiedenen Formaten
- Neuer Befehl: `vzd-cli admin <tu|ru|pu> edit <TELEMATIK_ID>`: editieren eines Basiseintrags in einem Text-Editor
- Neuer Ausgabeformat: `--table`, eine ASCII Tabelle
- Compatibility Modus zu 1.6 wurde entfernt um Abhängigkeiten im gesamten Projekt übersichtlicher zu haben.

== Version 2.0.0
- Kompatibilitätsmodus zur VZDClient 1.6. Befehl `vzd-cli admin cmd`
- Neue Befehle unter `vzd-cli pers`: verarbeitet die Basisdaten und Zertifikate aus den Peronalisierung-XML(TSP-Schnittstelle exports)
und schreibt diese in `vzd-cli` kompatiblen Format
- Neuer Befehl `vzd-cli admin delete-cert`: Löschen der Zertifikate
- Unterstützung für Admin API 1.8.1 https://github.com/gematik/api-vzd/blob/I_Directory_Administration/1.8.1/src/openapi/DirectoryAdministration.yaml
- Unterstützung von Paging in `vzd-cli admin dump create` über `-c / --cursor-size` und `-e / --expected-count`
- Anpassung der Konfiguration über `vzd-cli admin config set`
- Kleine Bugfixes


== Version 0.16.x
- Neue Befehle unter `vzd-cli ldif`: Management der LDIF-Exporten
- Dump Optimierungen
- Neue Spalten im CSV-Output
  - FAD - KIM Anbieter Kennung
  - specialization
- `vzd-cli admin cert-info` zeigt jetzt Title-Attribut (falls vorhanden)

== Version 0.15.x

- Unterstüzung von VZD 3.1.0-14
- `dump` Befehl wurde überarbeitet
  - `vzd-cli admin dump create` erzeugt einen neuen dump
  - `vzd-cli admin dump ocsp` ergänzt für jeden Zertifikat aus dem Dump die OCSP Informationen
  - Falls ein Dump bereits die OCSP-Daten enthält, werden nur die fehlerhafte Zertifikate erneut geprpüft (status != GOOD)
- neuer Befehl: `admin login-cred`: erlaubt Anmelden mit Client-Credentials, angegeben über Kommandozeile oder Umgebungsvariablen
- Befehle unterstützen zusätzlich zu `-p` die explizite Optionen:
```
      --name TEXT
      --uid TEXT
      --givenName TEXT
      --sn TEXT
      --cn TEXT
      --displayName TEXT
      --streetAddress TEXT
      --postalCode TEXT
      --countryCode TEXT
      --localityName TEXT
      --stateOrProvinceName TEXT
      --title TEXT
      --organization TEXT
      --otherName TEXT
      -t, --telematikID TEXT
      --specialization TEXT
      --domainID TEXT
      --holder TEXT
      --personalEntry [true|false]
      --dataFromAuthority [true|false]
      --professionOID TEXT
      --entryType INT
      --maxKOMLEadr INT
      --changeDateTimeFrom TEXT
      --changeDateTimeTo TEXT
      --baseEntryOnly [true|false]
```
- Kleine Anpassungen am CSV-Format
- Upgrade ktor.io Version 2.0.1

== Version 0.14.x

- Unterstützung der OCSP-Abfragen für X509-Zertifikate (s. `vzd-cli admin -o` oder `vzd-cli admin --ocsp`
- Unterstützung von CertHash Extension
- Neuer Befehl: `vzd-cli admin dump`: lädt große Mengen von Einträgen vom Server für nachfolgende loikale Verarbeitung
(z.B. Datenanalysen)
- Es werden mehr Zertifikatdetails angezeigt (z.B. einzelne Subject-Felder, OCSP-Responder-URL)
- CSV-Output Verbesserungen:
  - Spalte für Anzahl der KIM-Adressen
  - Spalte für Anzahl der Zertifikate
  - Spalte für Gültigkeit der Zertifikate

== Version 0.13.x

- Die Abfragen nach Vault-Password sind jetzt klarer
- Neuer Befehl: `vzd-cli admin vault purge` - löscht alle Credentials aus dem Vault
- Fix Bug beim Einloggen hinter dem Proxy-Server

== Version 0.12.x

- Konfiguration ist komplett neu geschrieben. 
- Neue Befehle 
  - `vzd-cli admin vault`
  - `vzd-cli admin config`
  - `vzd-cli admin login` 
- Proxy kann jetzt ein- und ausgeschaltet werden:
  - Proxy an: `vzd-cli admin -x list`
  - Proxy aus: `vzd-cli admin -X list`
- holder und domainID sind jetzt Teil von CSV-Output
- Skelett-Zertifikatsblöcke werden beim CSV-Output nicht mehr gezählt 
- Authentisierung wird jetzt nur beim Bedarf verlangt, z.B. `vzd-cli admin cert-info` funktioniert ohne Authentisierung. 
- Viele Bugfixes
