= Changelog `vzd-cli`

== Version 0.14.x

- Unterstützung der OCSP-Abfragen für X509-Zertifikate (s. `vzd-cli admin -o` oder `vzd-cli admin --ocsp`
- Neues Befehl: `vzd-cli admin dump`: lädt große Mengen von Einträgen vom Server für nachfolgende loikale Verarbeitung
(z.B. Datenanalysen)
- Es werden mehr Zertifikatdetails angezeigt (z.B. einzelne Subject-Felder, OCSP-Responder-URL)
- CSV-Output Verbesserungen:
  - Spalte für Anzahl der KIM-Adressen
  - Spalte für Anzahl der Zertifikate
  - Spalte für Gültigkeit der Zertifikate

== Version 0.13.x

- Die Abfragen nach Vault-Password sind jetzt klarer
- Neues Befehl: `vzd-cli admin vault purge` - löscht alle Credentials aus dem Vault
- Fix Bug beim Einloggen hinter dem Proxy-Server

== Version 0.12.x

- Konfiguration ist komplett neu geschrieben. 
- Neue Befehle 
  - `vzd-cli admin vault`
  - `vzd-cli admin config`
  - `vzd-cli admin login` 
- Proxy kann jetzt ein- und ausgeschaltet werden:
  - Proxy an: `vzd-cli admin -x list`
  - Proxy aus: `vzd-cli admin -X list`
- holder und domainID sind jetzt Teil von CSV-Output
- Skelett-Zertifikatsblöcke werden beim CSV-Output nicht mehr gezählt 
- Authentisierung wird jetzt nur beim Bedarf verlangt, z.B. `vzd-cli admin cert-info` funktioniert ohne Authentisierung. 
- Viele Bugfixes

== Backlog
