= Changelog `vzd-cli`

== Version 3.2.1

- `vzd-cli admin <ru|tu|pu> dump ocsp` hat nun die neue Parameter `--delay INT` und `--concurrency INT`

== Version 3.2.0

- Client kann jetzt als Backend for Frontend (BFF) für die Web-GUI verwendet werden `vzd-cli bff start`. Konfiguration erfolgt über die Umgebungsvariablen.
- Client kann jetzt im Docker ausgeführt werden, s. Dockerfile.

== Version 3.1.0

- `providedBy` in den Basisdaten und bei der Abfrage werden jetzt unterstützt
- `vzd-cli admin <ru|tu|pu> list` und `vzd-cli admin <ru|tu|pu> dump` unterstützen jetzt `--kim-mail` und `--kim-data` Optionen (neue Schnittstelle für die Suche über Fachanwendungsattribute)
- Aktualisierung der FHIR-Profile und Mappings auf die neueste Spezifikation
- Editieren der Einträge in der GUI
- Upgrade der GUI auf Angular 18 und neuesten Carbon Design System
- FHIR Umgebung wurde von `test` auf `tu` umgestellt.
- Bugfixes

== Version 3.0.0

- Unterstützung FHIR VZD FdV und Search Schnittstellen, s. `vzd-cli fhir`
- Neues Befehl für übergreifenden login: `vzd-cli login`
- Tägliche Überprüfung der Updates ist jetzt abschaltbar `vzd-cli config set updates.enabled true|false`
- Diverse Bugfixes

== Version 2.6.2
- TelematikID ist jetzt optional in `vzd-cli admin <ru|tu|pu> log`

== Version 2.6.1
- Set Februar/2024 werden OAuth2 Felder  refresh_token und session_state nicht mehr unterstützt. Beide Felder wurden optional gemacht.
- ktlint wurde auf die neueste Version aktualisiert

== Version 2.6.0
- Set Februar/2024 werden OAuth2 Felder  `refresh_token` und `session_state` nicht mehr unterstützt. Beide Felder wurden optional gemacht.
- ktlint wurde auf die neueste Version aktualisiert

== Version 2.6.0

- Abhängigkeiten und Build-Tools-Versionen aktualisiert
- Bugfixes

== Version 2.3.0
- `vzd-cli admin cert-info` ersetzt `vzd-cli admin <ru|tu|pu> cert-info`
- Abfrage der Änderungshistorie: `vzd-cli admin <ru|tu|pu> log`
- Validierungsergebnisse wurden in den Dump aufgenommen
- GUI Optimierungen

== Version 2.2.0
- Quellcode wurde in Vorbereitung der Web-Version des Clients modularisiert und umstrukturiert
- Microservice Client `directory-bff`
- Rudimentäre Validierung der Basiseinträge
- Versionen der Abhängigkeiten wurden aktualisiert
- Kompatibilität mit VZD 3.2.0 und Admin API 1.9.4
- `--human` Output Format ist jetzt deutlich kompakter und lesbar
- Neue Output Formate: `--yaml-ext` und `--json-ext`
- Zertifikate werden zu Smartcards gebündelt
- Attribut `kind` um welchen Eintrag es sich handelt (z.B. Apotheke oder Krankenhaus)
- `--meta` Option kann jetzt bei Anfragen genutzt werden

== Version 2.1.0
- CLI Interface wurde weitgehend überarbeiten un vereinfacht, s. Dokumentation
- Self-Update Funktion wurde implementiert, s. `vzd-cli update`
- Erste simple Web-GUI wurde hinzugefügt, s. `vzd-cli gui`
- Neu: ApoVZD Unterstützung über `vzd-cli apo`
- `vzd-cli admin <tu|ru|pu> login` wurde komplett überarbeitet
- `vzd-cli admin <tu|ru|pu> token` ersetzt `vzd-cli admin auth`
- Neuer Befehl: `vzd-cli admin <tu|ru|pu> search`: schnelle, intuitive Suche nach Einträgen
- Neuer Befehl: `vzd-cli admin <tu|ru|pu> show <TELEMATIK_ID>`: zeigt den gesamten Eintrag in verschiedenen Formaten
- Neuer Befehl: `vzd-cli admin <tu|ru|pu> edit <TELEMATIK_ID>`: editieren eines Basiseintrags in einem Text-Editor
- Neuer Ausgabeformat: `--table`, eine ASCII Tabelle
- Compatibility Modus zu 1.6 wurde entfernt um Abhängigkeiten im gesamten Projekt übersichtlicher zu haben.

== Version 2.0.0
- Kompatibilitätsmodus zur VZDClient 1.6. Befehl `vzd-cli admin cmd`
- Neue Befehle unter `vzd-cli pers`: verarbeitet die Basisdaten und Zertifikate aus den Peronalisierung-XML(TSP-Schnittstelle exports)
und schreibt diese in `vzd-cli` kompatiblen Format
- Neuer Befehl `vzd-cli admin delete-cert`: Löschen der Zertifikate
- Unterstützung für Admin API 1.8.1 https://github.com/gematik/api-vzd/blob/I_Directory_Administration/1.8.1/src/openapi/DirectoryAdministration.yaml
- Unterstützung von Paging in `vzd-cli admin dump create` über `-c / --cursor-size` und `-e / --expected-count`
- Anpassung der Konfiguration über `vzd-cli admin config set`
- Kleine Bugfixes


== Version 0.16.x
- Neue Befehle unter `vzd-cli ldif`: Management der LDIF-Exporten
- Dump Optimierungen
- Neue Spalten im CSV-Output
  - FAD - KIM Anbieter Kennung
  - specialization
- `vzd-cli admin cert-info` zeigt jetzt Title-Attribut (falls vorhanden)

== Version 0.15.x

- Unterstüzung von VZD 3.1.0-14
- `dump` Befehl wurde überarbeitet
  - `vzd-cli admin dump create` erzeugt einen neuen dump
  - `vzd-cli admin dump ocsp` ergänzt für jeden Zertifikat aus dem Dump die OCSP Informationen
  - Falls ein Dump bereits die OCSP-Daten enthält, werden nur die fehlerhafte Zertifikate erneut geprpüft (status != GOOD)
- neuer Befehl: `admin login-cred`: erlaubt Anmelden mit Client-Credentials, angegeben über Kommandozeile oder Umgebungsvariablen
- Befehle unterstützen zusätzlich zu `-p` die explizite Optionen:
```
      --name TEXT
      --uid TEXT
      --givenName TEXT
      --sn TEXT
      --cn TEXT
      --displayName TEXT
      --streetAddress TEXT
      --postalCode TEXT
      --countryCode TEXT
      --localityName TEXT
      --stateOrProvinceName TEXT
      --title TEXT
      --organization TEXT
      --otherName TEXT
      -t, --telematikID TEXT
      --specialization TEXT
      --domainID TEXT
      --holder TEXT
      --personalEntry [true|false]
      --dataFromAuthority [true|false]
      --professionOID TEXT
      --entryType INT
      --maxKOMLEadr INT
      --changeDateTimeFrom TEXT
      --changeDateTimeTo TEXT
      --baseEntryOnly [true|false]
```
- Kleine Anpassungen am CSV-Format
- Upgrade ktor.io Version 2.0.1

== Version 0.14.x

- Unterstützung der OCSP-Abfragen für X509-Zertifikate (s. `vzd-cli admin -o` oder `vzd-cli admin --ocsp`
- Unterstützung von CertHash Extension
- Neuer Befehl: `vzd-cli admin dump`: lädt große Mengen von Einträgen vom Server für nachfolgende loikale Verarbeitung
(z.B. Datenanalysen)
- Es werden mehr Zertifikatdetails angezeigt (z.B. einzelne Subject-Felder, OCSP-Responder-URL)
- CSV-Output Verbesserungen:
  - Spalte für Anzahl der KIM-Adressen
  - Spalte für Anzahl der Zertifikate
  - Spalte für Gültigkeit der Zertifikate

== Version 0.13.x

- Die Abfragen nach Vault-Password sind jetzt klarer
- Neuer Befehl: `vzd-cli admin vault purge` - löscht alle Credentials aus dem Vault
- Fix Bug beim Einloggen hinter dem Proxy-Server

== Version 0.12.x

- Konfiguration ist komplett neu geschrieben. 
- Neue Befehle 
  - `vzd-cli admin vault`
  - `vzd-cli admin config`
  - `vzd-cli admin login` 
- Proxy kann jetzt ein- und ausgeschaltet werden:
  - Proxy an: `vzd-cli admin -x list`
  - Proxy aus: `vzd-cli admin -X list`
- holder und domainID sind jetzt Teil von CSV-Output
- Skelett-Zertifikatsblöcke werden beim CSV-Output nicht mehr gezählt 
- Authentisierung wird jetzt nur beim Bedarf verlangt, z.B. `vzd-cli admin cert-info` funktioniert ohne Authentisierung. 
- Viele Bugfixes
