= 🗂️ `vzd-cli`: Command Line Client für Verzeichnisdienst der TI 
:toc: auto

`vzd-cli` wurde in Vorbereitung der Migration des gematik Verzeichnisdienstes (VZD) von LDAP nach FHIR entwickelt. Über ein modernes CLI (Command Line Interface) können neue und alte Schnittstellen des VZD genutzt werden.

== Installation

1. Download link:https://github.com/spilikin/app-vzd-cli/releases[Latest Release] von `vzd-cli` von github.
2. ``vzd-cli-<VERSION>.zip`` extrahieren 
3. Die Skripte in bin/ benutzen um `vzd-cli` zu starten

[source]
----
$ bin/vzd-cli --help
Usage: vzd-cli [OPTIONS] COMMAND [ARGS]...

Options:
  --env FILENAME  specify env file
  --version       Show the version and exit
  -h, --help      Show this message and exit

Commands:
  admin  CLI for DirectoryAdministration API
----

== Schnellstart

Aufbau der CLI folgt aktuellen Best-Practices analog z.B. zu Docker, Kubernetes, Helm.

.File namens `.env` im aktuellen Ordner anlegen:
[source,bash]
----
ADMIN_API_URL=https://vzdpflege-ref.vzd.ti-dienste.de:9543/
ADMIN_AUTH_URL=https://auth-ref.vzd.ti-dienste.de:9443/auth/realms/RSDirectoryAdministration/protocol/openid-connect/token
ADMIN_CLIENT_ID=<client id>
ADMIN_CLIENT_SECRET=<client secret>
#HTTP_PROXY_URL=http://192.168.110.10:3128/
----
.Beispiel: Suche nach einem Eintrag mit angegebenen telematikID
[source,bash]
----
bin/vzd-cli admin list --param telematikID=5-SMC-B-Testkarte-883110000092568
----

== `admin`: CLI für Directory Administration 

=== Configuration

|===
|Variable | Beschreibung 
|`ADMIN_API_URL`
| URL des Directory Administration API Endpoints 

|`ADMIN_AUTH_URL` +
`ADMIN_CLIENT_ID` +
`ADMIN_CLIENT_SECRET`
| Authentisierungsinformation 

|`ADMIN_ACCESS_TOKEN`
| Alternativ kann Access-Token als Umgebungsvariable gesetzt werden. Dadurch können mehrere Aufrufe des Clients ohne expliziten Authentisierung durchgeführt werden.

Benutzt <<cmd-admin-auth,admin auth>> um den Token zu besorgen.

|`HTTP_PROXY_URL`
| Optional: URL zum HTTP-Proxy, z.B.: `http://192.168.110.10:3128/`

|===

Die Umgebungsvariablen können in einer `.env` Datei gespeichert werden. Hier ist ein Beispiel für die Referenzumgebung:

[source,bash]
----
ADMIN_API_URL=https://vzdpflege-ref.vzd.ti-dienste.de:9543/
ADMIN_AUTH_URL=https://auth-ref.vzd.ti-dienste.de:9443/auth/realms/RSDirectoryAdministration/protocol/openid-connect/token
ADMIN_CLIENT_ID=<client id>
ADMIN_CLIENT_SECRET=<secret>
----

Standardmäßig wird die Datei mit Namen `.env` im aktuellen Arbeitsverzeichnis geladen. Alternativer Dateiname kann über  `--env` Option angegeben werden:

[source,bash]
----
bin/vzd-cli --env ../.env.ru admin list
----

[#cmd-admin-info]
=== `admin info`

Zeigt die Information über den VZD-Server und die API.

[source,bash]
----
bin/vzd-cli admin info
----


[#cmd-admin-auth]
=== `admin auth`

Authentisiert den Client und gibt `ACCESS_TOKEN` zurück. Token kann danach in der Umgebungsvariable `ADMIN_ACCESS_TOKEN` gespeichert werden, damit weitere Client-Aufrufe keine erneute explizite Authentisierung durchführen müssen.

.Beispiel: Authentisiert und speichert den ACCESS_TOKEN in die Umgebungsvariable 
[source,bash]
----
export ADMIN_ACCESS_TOKEN=`bin/vzd-cli admin auth`
----

[#cmd-admin-list]
=== `admin list`

==== Optionen
* `--param` oder `-p` +
Setzt einen Query-Parameter bei der Suche der Einträge über die API. Kann mehrfach angegeben werden um die Parameter zu kombinieren. +
Die Liste von gültigen Parametern kann aus https://github.com/gematik/api-vzd/blob/master/src/openapi/DirectoryAdministration.yaml[DirectoryAdministration API] entnommen werden (s. `read_Directory_Entry`)

* `--param-file` oder `-f` +
Liest Werte eines Parameters aus der Datei und fragt für jeden Wert nach Eintrag im VZD ab. Die Datei soll den gewünschten Wert einmal pro Zeile enthalten:

.Beispiel: Findet alle Einträge mit TelematikID aus `telematik.txt`
[source,bash]
----
bin/vzd-cli admin --short list -f telematikID telematik.txt
----

.Inhalt von `telematik.txt`
----
4-SMC-B-Testkarte-883110000093329
3-SMC-B-Testkarte-883110000093294
2-SMC-B-Testkarte-883110000093645
3-SMCB-Testkarte-883110000092193
----


Suche und Anzeige von Verzeichnisdiensteinträgen.

[#cmd-admin-template]
=== `admin template`

Generiert die Dateivorlagen für `admin add` oder `admin modify` Befehle.

.Beispiel: Erzeugt eine Vorlage und schreibt es in eine YAML-Datei 
[source,bash]
----
bin/vzd-cli admin template base > Eintrag.yaml
----

.Beispiel: Erzeugt eine Vorlage und schreibt es in eine JSON-Datei 
[source,bash]
----
bin/vzd-cli admin --json template base > Eintrag.json
----

[#cmd-admin-add-base]
=== `admin add-base`

Neuen Verzeichnisdiensteintrag erstellen.

[#cmd-admin-load-base]
=== `admin load-base`

Lädt einen Basiseintrag. Die geladene Struktur kann als Datei gespeichert werden, in einem Text-Editor bearbeitet und anschließend mit `admin modify-base` modifiziert werden.

[#cmd-admin-modify-base]
=== `admin modify-base`

Modifiziert den gesamten Basiseintrag im Verzeichnisdienst.

[#cmd-admin-modify-base-attr]
=== `admin modify-base-attr`

Modifiziert einzelne Attribute des Basiseintrags

[#cmd-admin-delete]
=== `admin delete`

Löscht Einträge aus dem Verzeichnisdienst.

[#cmd-admin-list-cert]
=== `admin list-cert`

Suche und Anzeige von X509-Zertifikaten.

[#cmd-admin-add-cert]
=== `admin add-cert`

Fügt einen neuen X509-Zertifikat zu existierenden Verzeichnisdiensteintrag hinzu.

[source,bash]
----
# zuerst einen leeren Basiseintrag erzeugen
bin/vzd-cli admin add-base -s telematikID=1-123123
# danach Zertifikat hinzufügen
# Achtung: TelematikID beim Befehl admin add-base und im Zertifikat müssen identisch sein
bin/vzd-cli admin add-cert 1-123123.der
----

[#cmd-admin-clear-cert]
=== `admin clear-cert`

Löscht alle Zertifikate aus dem angegeben Eintrag.

[source,bash]
----
bin/vzd-cli admin clear-cert -p telematikID=1-123123
----

[#cmd-admin-save-cert]
=== `admin save-cert`

Speichert alle gefundene Zertifikate in ein Verzeichnis

[#cmd-admin-delete-cert]
=== `admin delete-cert`

WARNING: Nicht implementiert

Löscht einen X509-Zertifikat.

